// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChPZ6hJ1igOER8azGhDYOOdc0exN0T2Do',
    appId: '1:1060305160473:web:fac0275e88561465d7dd88',
    messagingSenderId: '1060305160473',
    projectId: 'fraction-2',
    authDomain: 'fraction-2.firebaseapp.com',
    storageBucket: 'fraction-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0rb0dprPTBU2oeXOgSgB5i750Bir_g6E',
    appId: '1:1060305160473:android:af07f9cf9478e83bd7dd88',
    messagingSenderId: '1060305160473',
    projectId: 'fraction-2',
    storageBucket: 'fraction-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeg3jyrXzxcXouOms6CBBxhRk6Cx9D2ao',
    appId: '1:1060305160473:ios:63f572c12c8e629ed7dd88',
    messagingSenderId: '1060305160473',
    projectId: 'fraction-2',
    storageBucket: 'fraction-2.appspot.com',
    iosClientId: '1060305160473-b2219qafdgagstomo5f9tr80lea9kp0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.fraction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeg3jyrXzxcXouOms6CBBxhRk6Cx9D2ao',
    appId: '1:1060305160473:ios:97e21ebbf22ba5eed7dd88',
    messagingSenderId: '1060305160473',
    projectId: 'fraction-2',
    storageBucket: 'fraction-2.appspot.com',
    iosClientId: '1060305160473-4ea5ug1hbpso5pe489t176mdptscshcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fraction.RunnerTests',
  );
}
