// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzTRHRD6NPDrmed2xEnfzy0sWeOAQw3nI',
    appId: '1:602053818051:web:786b42afefc221eef25476',
    messagingSenderId: '602053818051',
    projectId: 'fraction-c7e1e',
    authDomain: 'fraction-c7e1e.firebaseapp.com',
    storageBucket: 'fraction-c7e1e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_2kkecX_bSKY43Olj3e5Ma8yeMpIaQDA',
    appId: '1:602053818051:android:a39989c75acc7ad2f25476',
    messagingSenderId: '602053818051',
    projectId: 'fraction-c7e1e',
    storageBucket: 'fraction-c7e1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD2Oc1s-CR2vdW8sQLY1i8nHmkcIoQzjQ',
    appId: '1:602053818051:ios:43f790140c22bf5af25476',
    messagingSenderId: '602053818051',
    projectId: 'fraction-c7e1e',
    storageBucket: 'fraction-c7e1e.appspot.com',
    androidClientId: '602053818051-crf6ps5k3gri5ih2r8jjpn4nlde96e6l.apps.googleusercontent.com',
    iosClientId: '602053818051-3q005fq3hveepg69i1u2op0ih07da3df.apps.googleusercontent.com',
    iosBundleId: 'com.example.fraction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD2Oc1s-CR2vdW8sQLY1i8nHmkcIoQzjQ',
    appId: '1:602053818051:ios:29cb9fe6e6e84d91f25476',
    messagingSenderId: '602053818051',
    projectId: 'fraction-c7e1e',
    storageBucket: 'fraction-c7e1e.appspot.com',
    androidClientId: '602053818051-crf6ps5k3gri5ih2r8jjpn4nlde96e6l.apps.googleusercontent.com',
    iosClientId: '602053818051-o0sg9s2v75thdf12cpmjo4aq2vtrsl6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.fraction.RunnerTests',
  );
}
